CREATE DATABASE IF NOT EXISTS `learn_nacos`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;

CREATE DATABASE IF NOT EXISTS `learn_mall`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;
