server:
  port: 9100

spring:
  config:
    import: optional:classpath:application-learn-mall-defaults.yml
  application:
    name: learn-demo
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        ip: 127.0.0.1

learn:
  mall:
    nacos:
      force-local-ip: true
      discovery-ip: 127.0.0.1

feign:
  inside:
    key: learn-mall
    secret: learn-mall-secret

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
